name: Build Go Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Create bin directory
      run: mkdir -p ./bin

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o ./bin/app-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} main.go

    - name: Debug bin directory
      run: ls -la ./bin

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: go-binaries
        path: ./bin/*
