# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64] # Add more architectures if needed (e.g., arm64)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Adjust the Go version to your project requirement

    - name: Build binary
      run: |
        env GOOS=windows GOARCH=amd64 go build -o .bin/app-saradoplaylistreplacement.exe main.go
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: go-binaries
        path: ./bin/*
